### PR TITLE
doc Finagle: serve should be serveIface

### PR DESCRIPTION
**Pull request by evanj**
I didn't follow the example exactly, but in getting starting with my own project this needs to be serveIface.

### CODE REVIEW

**Comment by babyman** [comment]
Thank you, to bad this batch has not made it to the documentation.

**Comment by taylorleese** [comment]
@mosesn @kevinoliver Can we get this a shipit label so we can get it merged?

**Comment by mosesn** [comment]
@taylorleese I think this preceded the shipit label–if you see anything else that has a couple LGTMs, feel free to add it yourself :sparkles:

**Comment by taylorleese** [comment]
@mosesn Yeah, will do. This was just so old I wanted to make sure it was still valid.

**Comment by kevinoliver** [comment]
@taylorleese I don't think this applies anymore.

**Comment by mosesn** [comment]
@kevinoliver why not?  This still looks wrong, even on `develop`.

https://github.com/twitter/scrooge/blob/develop/doc/src/sphinx/Finagle.rst#creating-a-server

**Comment by kevinoliver** [comment]
@mosesn indeed. i was looking in Finagle's docs, not Scrooge's. i'll reopen and pull this in.

**Comment by kevinoliver** [comment]
Ok got this merged in locally @evanj. Thanks for the patch, it should show up on the `develop` on Monday.

**Pull request closed without merging**
