### PR TITLE
rebase experimental-java RHS struct PR

### PR DESCRIPTION
**Pull request by pavanch007**
rebased the pull request from @eirslett  https://github.com/twitter/scrooge/pull/137

### CODE REVIEW

**Comment by pavanch007** [comment]
Hi @eirslett I rebased your fix .. can you take a look?

**Comment by nshkrob** [comment]
Do you mind adding a basic test for this?

**Comment by eirslett** [comment]
LGTM!
@nshkrob I have a test case for #202 that will also test the builder. (But I need this PR to be merged first)

**Comment by eirslett** [comment]
This PR is now a part of #202 so it can be closed.

**Comment by pavanch007** [comment]
Thanks for taking care of this @eirslett ! I'll close the PR

**Pull request closed without merging**
