### PR TITLE
Add crossbuild for sbt 1.0.2

### PR DESCRIPTION
**Pull request by muuki88**
## Cross build sbt-plugin

This pull requests starts the sbt 1.x cross building support.

- [x] cross building
- [ ] add scripted tests
- [ ] described release process

### CODE REVIEW

**Comment by mosesn** [comment]
@muuki88 thanks for the PR!  I actually have a local branch which sets up cross building for sbt 1.0.x and migrates scrooge and friends to 1.0.x though, so we're probably going to be using that one.  Right now we're just waiting on the latest OSS maven release–we're a bit behind schedule, so we decided not to do anything that could potentially complicate the release, but it should be out soon.

**Comment by muuki88** [comment]
Nice ! 😊 I played a bit with upgrading the build to SBT 1.x as well, but that requires some plugin updates and changes.

If you take care of this we can close this PR, right?

**Comment by mosesn** [comment]
@muuki88 sounds like a plan.

**Comment by mosesn** [comment]
@muuki88 merged in [here](https://github.com/twitter/scrooge/commit/d3499b89fbee72766d95b89e3f7c323272b3dce7), thanks!

**Comment by muuki88** [comment]
Wuhuuuu 🎊🎉🎉🎊

**Comment by muuki88** [comment]
I left some notes on the commit.

**Pull request closed without merging**
