### PR TITLE
Make flag support type safe through the sbt plugin

### PR DESCRIPTION
**Pull request by jedesah**
This has the added advantage of bypassing the huge parsing step that didn’t ever really need to be called, so should make things altogether faster on top of avoiding weird behavior. Does it really make much sense to supply the “-help” in your sbt build?

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM, let's see if we can merge this in!

**Comment by mosesn** [comment]
This is extremely stupid, but adding some of these flags tips us over the edge to too many arguments for sbt.  It only [goes up to 11][0].  So I removed experimental flags because we don't seem to use them anywhere.

[0]: https://github.com/sbt/sbt/blob/1.0.x/main-settings/src/main/scala/sbt/Structure.scala#L374

**Comment by jedesah** [comment]
@mosesn Do you want me to rebase this or are you going to do that as part of your internal merging process (twitter open source still works that way?)?

**Comment by mosesn** [comment]
Yeah, I'll do it as part of the internal merging process, thanks!  It's up for review internally now.

**Comment by mosesn** [comment]
This made it to `develop` here: https://github.com/twitter/scrooge/commit/5979724d4ac92f6b895847e0ebc7a5a67475fa85 thanks so much!  Really sorry about how long this took.

**Pull request closed without merging**
