### PR TITLE
Clarify default for scroogeThriftOutputFolder

### PR DESCRIPTION
**Pull request by dossett**
Problem

The explanation for the default value of `scroogeThriftOutputFolder` is out of date. The default output is now `sourceManaged/thrift`.  

The output of `git diff scrooge-4.7.0 -- src/main/scala/com/twitter/ScroogeSBT.scala` shows, in part, this:

```diff
-    scroogeThriftOutputFolder <<= (sourceManaged) { identity },
+    scroogeThriftOutputFolder in Compile := (sourceManaged in Compile).value / "thrift",
+    scroogeThriftOutputFolder in Test := (sourceManaged in Test).value / "thrift",
```

### CODE REVIEW

**Comment by mosesn** [comment]
Looks good to me @dossett.  Were you able to test this out?

**Comment by dossett** [comment]
Hi @mosesn since I was just updating the comment string, I didn't test and deploy locally.  I actually wasn't able to get the entire project to build, but I didn't try too hard either.

**Comment by mosesn** [comment]
Oh, duh, I don't know what I was thinking.  I'll pull this in, thanks!

**Comment by mosesn** [comment]
@dossett this was merged in https://github.com/twitter/scrooge/commit/792fd68be06e79e88936b57a4c3c5c78c8dc4c3c and has since been released in scrooge-sbt-plugin 18.3.0.  thanks!

**Comment by dossett** [comment]
Great!

**Pull request closed without merging**
