### PR TITLE
Fix deprecations in scrooge-sbt-plugin

### PR DESCRIPTION
**Pull request by 3tty0n**
Problem

There are many deprecated methods in `ScroogeSBT.scala` like ( `<<=`, `<+=` ).

Solution

Change them to the recommended style.

Result

ScroogeSBTPlugin can be used in sbt 1.0.x.

### CODE REVIEW

**Comment by mosesn** [comment]
@3tty0n I made a breaking API change to twitter commons, which makes it difficult for us to build scrooge & friends.  I'm planning on removing the dependency on twitter commons (which is why I made the change!) but in the mean time, we can't safely publish without risking breaking the build, so I'm going to hold off on merging this in for a few days until we remove the dependency completely.  Sorry for the delay!

**Comment by mosesn** [comment]
@3tty0n finally got this out to github!  thanks for bearing with me.  f978e10e7c42c38784e6ca26f6f373f2bcee06c9

**Comment by mosesn** [comment]
ugh wrong link.  your thing should be out in an hour or two, my bad!

**Comment by mosesn** [comment]
Here's the right link, sorry about the confusion: https://github.com/twitter/scrooge/commit/5ebbf79a47871f8ac228fcb505462cdc2599dd8f

**Comment by 3tty0n** [comment]
@mosesn Thank you for your kind support!

**Pull request closed without merging**
