### PR TITLE
add twitter repo to SBT plugin docs

### PR DESCRIPTION
**Pull request by gidsg**
Please see https://github.com/twitter/scrooge/pull/207 for history.

### CODE REVIEW

**Comment by dschobel** [comment]
LGTM

**Comment by nshkrob** [comment]
Ship it!

**Comment by mosesn** [comment]
LGTM

**Comment by dschobel** [comment]
@gidsg thanks for the contribution! this PR has been merged internally and will sync out to the develop branch on Monday.

**Comment by vkostyukov** [comment]
This has been merged [here](https://github.com/twitter/scrooge/commit/b1c87cf8ca366b707365787f1b13a8af816e0ec3). So closing it.

**Pull request closed without merging**
